repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.11.4

#-   repo: local
#    hooks:
#    - id: npm-build
#      name: npm build
#      stages: [commit]
#      language: script
#      entry: ./build.sh
